services:
  client:
    build: ./client
    ports:
      - "5173:5173"
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build: ./server
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
volumes:
  postgres_db:
