apiVersion: v1
kind: ConfigMap
metadata:
  name: mern-configmap
data:
  MONGO_URL: mongo-service
---
apiVersion: v1
kind: Secret
metadata:
  name: mern-secret
type: Opaque
data:
  MONGODB_USERNAME: YWRtaW4=
  MONGODB_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mern-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-db
  template:
    metadata:
      labels:
        app: mern-db
    spec:
      containers:
      - name: mern-db
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mern-secret
              key: MONGODB_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mern-secret
              key: MONGODB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mern-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: mern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern
  template:
    metadata:
      labels:
        app: mern
    spec:
      containers:
      - name: mern
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mern-secret
              key: MONGODB_USERNAME 
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mern-secret
              key: MONGODB_PASSWORD
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mern-configmap
              key: MONGO_URL
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: mern
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30007

