apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment
  labels:
    app: secret
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secret
  template:
    metadata:
      labels:
        app: secret
    spec:
      containers:
      - name: secret
        image: secret
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env: 
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: secret-configmap
                key: JWT_SECRET
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cm-secret
                key: DB_PASSWORD
